/* eslint-disable functional/functional-parameters */
/* eslint-disable functional/no-expression-statement */
import { AAxError, tryToCatch } from '@helpers'

describe('Exception handling', () => {
    test('no args', async () => {
        // @ts-ignore
        const res = await tryToCatch('error')
        expect(res[0]).toBeInstanceOf(AAxError)
    })
})
